# Generated by Django 2.2.4 on 2020-07-30 07:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='vectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Vector',
        ),
    ]
